---
layout: cv
title: Brandon's Resume
---
# Brandon Van Blarcum
Software Engineering Major at Brigham Young University - Idaho

<div id="webaddress">
<a href="mailto:brandonjvanb@gmail.com">brandonjvanb@gmail.com</a>
| <a href="https://www.linkedin.com/in/brandon-j-van-blarcum/">My LinkedIn page</a>
</div>


## Currently

Junior at Brigham Young University - Idaho

### Specialized in

- Programming Languages: Python, Java, C++, MySQL, HTML, CSS, JavaScript, Java, Kotlin

- Platforms and Frameworks: Jupyter, MongoDB, Kubernetes, Flask, Docker

- Experienced with managing projects with Git


### Research interests

- Software development

- Full stack development



## Education

`Jan 2021 – Dec 2027`
__Brigham Young University - Idaho__


## Awards

`2018`
Participant, *Lockheed Martin Deer Creek*, Littleton, CO
Qualified and participated for Code Quest 2018 hosted by Lockheed Martin

`2013-2018`
Participant, *Colorado TSA*, Denver, CO
Competed in the Colorado State Technology Student Association (TSA) competition for five years

`2018`
Eagle Scout, *Boy Scouts of America*, Parker, CO
Earned the Eagle Scout from the Boy Scouts of America


## Occupation

`Mar 2023 - Sept 2023, Apr 2024 - Aug 2024, Apr 2025 - Aug 2025`
__ICR, Inc__, Aurora

- Software Engineer Intern
- Learned and expanded upon an existing codebase to store open-source data from a series of websites. This data was then used for data analytics.
- Created custom python scripts tuned for extracting open source data.
- Rebuilt Grafana dashboards to display the data for administrative use.

<!-- ### Footer

Last updated: April 2026 -->